config/routes.rb
Rails.application.routes.draw do
  
  resources :clients
  resources :pets
  
  resources :pet_histories
  root 'clients#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets

    def registered_pets
        pets.count
    end
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :pet_histories
    belongs_to :client
    #pertenece a un cliente

    #para contar la cantidad de historiales de una mascota
    def history_count
        pet_histories.count
    end
    
    #AVERAGE ES UN MÉTODO PARA SACAR PROMEDIOS
    #Para hacer el promedio del peso
    def avg_weight
        pet_histories.average(:weight)
    end

    #Para el promedio del tamaño
    def avg_height
        pet_histories.average(:height)
    end

    #Para obtener el peso máximo del historia
    def max_weight
        pet_histories.pluck(:weight)
    end

    #PLUCK es para que te muestre la info en arreglos, en este caso el peso máximo
    def pluck_weight
        pet_histories.pluck(:weight)
    end

    #Para relacionar al dueño con la mascota
    def owner_name
        client&.name
    end

end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: %i[ show edit update destroy ]

  # GET /pet_histories or /pet_histories.json
  def index
    @pet_histories = PetHistory.all
  end

  # GET /pet_histories/1 or /pet_histories/1.json
  def show
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
    @pets = Pet.pluck :name, :id
  end

  # GET /pet_histories/1/edit
  def edit
    @pets = Pet.pluck :name, :id
  end

  # POST /pet_histories or /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to pet_history_url(@pet_history), notice: "Pet history was successfully created." }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1 or /pet_histories/1.json
  def update
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to pet_history_url(@pet_history), notice: "Pet history was successfully updated." }
        format.json { render :show, status: :ok, location: @pet_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1 or /pet_histories/1.json
  def destroy
    @pet_history.destroy

    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: "Pet history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_history_params
      params.require(:pet_history).permit(:weight, :height, :diagnosis, :pet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @clients = Client.pluck :name, :id
  end

  # GET /pets/1/edit
  def edit
    @clients = Client.pluck :name, :id
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :race, :birth, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Nombre:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= client.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Registro de mascota</strong>
    <%= client.registered_pets %>
  </p>
  <!--Esto se relaciona con el modelo client.rb, para poder registrar una mascota, contabilizada en la vista de los clientes registrados-->

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinaria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pet_histories/_form.html.erb
<%= form_with(model: pet_history) do |form| %>
  <% if pet_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
        <% pet_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :diagnosis, style: "display: block" %>
    <%= form.text_field :diagnosis %>
  </div>

  <div>
    <%= form.label :pet_id, style: "display: block" %>
    <%= form.select :pet_id, options_for_select(@pets) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pet_histories/_pet_history.html.erb
<div id="<%= dom_id pet_history %>">
  
   <p>
    <strong>Mascota:</strong>
    <%= pet_history.pet_id %>
  </p>
  
  <p>
    <strong>Peso:</strong>
    <%= pet_history.weight %>
  </p>

  <p>
    <strong>Tamaño:</strong>
    <%= pet_history.height %>
  </p>

  <p>
    <strong>Diagnóstico:</strong>
    <%= pet_history.diagnosis %>
  </p>


</div>

app/views/pet_histories/edit.html.erb
<h1>Editing pet history</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Show this pet history", @pet_history %> |
  <%= link_to "Back to pet histories", pet_histories_path %>
</div>

app/views/pet_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Historial</h1>

<div id="pet_histories">
  <% @pet_histories.each do |pet_history| %>
    <%= render pet_history %>
    <p>
      <%= link_to "Show this pet history", pet_history %>
    </p>
  <% end %>
</div>

<%= link_to "New pet history", new_pet_history_path %>

app/views/pet_histories/new.html.erb
<h1>Nuevo historial</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Back to pet histories", pet_histories_path %>
</div>

app/views/pet_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet_history %>

<div>
  <%= link_to "Edit this pet history", edit_pet_history_path(@pet_history) %> |
  <%= link_to "Back to pet histories", pet_histories_path %>

  <%= button_to "Destroy this pet history", @pet_history, method: :delete %>
</div>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :race, style: "display: block" %>
    <%= form.text_field :race %>
  </div>

  <div>
    <%= form.label :birth, style: "display: block" %>
    <%= form.date_field :birth %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Nombre:</strong>
    <%= pet.name %>
  </p>

  <p>
    <strong>Raza:</strong>
    <%= pet.race %>
  </p>

  <p>
    <strong>Nacimiento:</strong>
    <%= pet.birth %>
  </p>

  <p>
    <strong>Dueño mascota:</strong>
    <%= pet.owner_name %> <!--Remite al método owner_name de model/pets.rb-->
  </p>

  <p>
    <strong>Historial:</strong>
    <%= pet.history_count %> <!--Remite al método history_count de model/pets.rb-->
  </p>

  <p>
    <strong>Diagnóstico:</strong>
    <%= pet.pet_histories.each do |pet_history| %> <!--Remite al diagnóstico, se hace un each para que vaya aumentando el número de diagnósticos-->
      <%= pet_history.diagnosis %>
    <% end %>
  </p>

</div>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Show this pet", @pet %> |
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mascotas</h1>

<div id="pets">
  <% @pets.each do |pet| %>
    <%= render pet %>
    <p>
      <%= link_to "Show this pet", pet %>
    </p>
  <% end %>
</div>

<%= link_to "New pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>Agregar nueva mascota</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", pets_path %>

  <%= button_to "Destroy this pet", @pet, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav>
    <%= link_to 'clientes', clients_path %>
    <%= link_to 'pets', pets_path %>
    <%= link_to 'pet_histories', pet_histories_path %>
</nav>